[server]
port = 4000
secret_key = "secret"
allow_origins = ["http://localhost:4000"]
[postgres]
url = "postgres://portfolio:Portfolio@localhost:5432/portfolio_local"
[redis]
url = "redis://localhost:6379"
[clients]
[clients.coingecko]
api_key = "your_api_key"
[logging]
level = "debug"
